name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # 🔥 SSH Agent만 사용
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 16.170.228.47 >> ~/.ssh/known_hosts

      - name: Deploy to Server with rsync
        run: |
          rsync -avz build/libs/*.jar ubuntu@16.170.228.47:~/app

      - name: Run SSH commands
        run: |
          ssh ubuntu@16.170.228.47 << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar ~/app/jenkins-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
          EOF
