name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 16.170.228.47 >> ~/.ssh/known_hosts

      - name: Deploy with Docker (Private Repo)
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          ssh ubuntu@16.170.228.47 \
            DOCKER_USER="$DOCKER_USER" \
            DOCKER_PASS="$DOCKER_PASS" \
            bash -s << 'EOF'
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              cd ~/app
              docker compose pull
              docker compose up -d --force-recreate
          EOF
